# -*- coding: utf-8 -*-
"""test_identification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sstJhtXqi2x2fHiBP978OjokVpaISSIa
"""

import unittest
from models.identification_model import identify_objects

class TestIdentification(unittest.TestCase):

    def setUp(self):

        self.test_image = 'image.jpg'  # image for testing

    def test_identify_objects(self):
        identified_objects = identify_objects(self.test_image)
        self.assertIsInstance(identified_objects, list, "The output should be a list of identified objects.")

    def tearDown(self):
        pass

if __name__ == '__main__':
    unittest.main()