# -*- coding: utf-8 -*-
"""test_summarization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sstJhtXqi2x2fHiBP978OjokVpaISSIa
"""

import unittest
from models.summarization_model import summarize_data

class TestSummarization(unittest.TestCase):

    def setUp(self):
        self.test_data = [{'id': 1, 'label': 'Object 1', 'details': 'Some details about object 1'}]

    def test_summarize_data(self):
        """Test the data summarization function."""
        summary = summarize_data(self.test_data)
        self.assertIsInstance(summary, dict, "The output should be a dictionary.")
        self.assertIn('summary', summary, "The summary should contain the 'summary' key.")
        self.assertGreater(len(summary['summary']), 0, "The summary should not be empty.")

    def tearDown(self):
        pass

if __name__ == '__main__':
    unittest.main()