# -*- coding: utf-8 -*-
"""test_text_extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sstJhtXqi2x2fHiBP978OjokVpaISSIa
"""

import unittest
from models.text_extraction_model import extract_text

class TestTextExtraction(unittest.TestCase):

    def setUp(self):
        self.test_image = 'image.jpg'  #image with text

    def test_extract_text(self):
        """Test the text extraction function."""
        extracted_text = extract_text(self.test_image)
        self.assertIsInstance(extracted_text, str, "The output should be a string containing extracted text.")
        self.assertGreater(len(extracted_text), 0, "The extracted text should not be empty.")

    def tearDown(self):
        pass

if __name__ == '__main__':
    unittest.main()